branches:
    only:
        - master

sudo: required
dist: trusty

language: python
python:
    - "2.7"
    - "3.4"

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y python-flake8 pylint

install:
    - pip install coverage
    - python setup.py install

script:
    - nosetests
    - flake8 cqlmapper/
    - pylint --errors-only cqlmapper/
